version: '3.8'

services:
  minio-server:
    image: quay.io/minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ADMIN
      MINIO_ROOT_PASSWORD: MINIOADMIN
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: main-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  graphdb:
    image: neo4j:5.12.0
    container_name: graph-db
    restart: unless-stopped
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - neo4j-data:/data
    environment:
      NEO4J_AUTH: "neo4j/pleaseletmein"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'

  fileserver-service:
    image: files-api
    container_name: files-api
    build:
      context: ./fileserver-service
      dockerfile: Dockerfile
    expose:
      - 7004
    ports:
      - "7004:7004"
    volumes:
      - ./fileserver-service:/app

    
  # redis-server:
  # exchanges-service:
  # background-workers:
  gateway:
    image: traefik:v2.11.21
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  
      - "./gateway:/etc/traefik"
  # messages-service:
  # recommandation-service:


volumes:
  mongo-data:
  neo4j-data:
  # files-api:

