version: '3.8'

services:
  minio:
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: main-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  graphdb:
    image: neo4j:5.12.0
    container_name: graph-db
    restart: unless-stopped
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - neo4j-data:/data
    environment:
      NEO4J_AUTH: "neo4j/pleaseletmein"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'

  fileserver-service:
  redis-server:
  exchanges-service:
  background-workers:
  gateway:
  messages-service:
  recommandation-service:



volumes:
  mongo-data:

  