api:
  insecure: true

log:
  level: INFO

providers:
  docker: 
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yaml  
    watch: true

entryPoints:
  web: 
    address: ":80"
  websecure:
    address: ":443"    