api:
  insecure: true

log:
  level: INFO

providers:
  docker: 
    watch: true
    exposedByDefault: false
  file:
    filename:  

entryPoints:
  web: 
    address: ":80"
  websecure:
    address: ":443"    